### ISSUE TITLE
 Cannot find module 'highcharts' type error after updating highcharts to 10.2.1

### ISSUE THREAD

**Issue by csprle** [highcharts/highcharts-react#378]
In my project I have `highcharts` and `highcharts-react-offical` installed. 

```json
{
  "highcharts": "^10.2.1",
  "highcharts-react-official": "^3.1.0",
}
```

After updating highcharts to latest version (10.2.1) I get the following error while checking types (`npm exec tsc`):

```node
node_modules/highcharts-react-official/dist/highcharts-react.min.d.ts:6:29 - error TS2307: Cannot find module 'highcharts' or its corresponding type declarations.

6 import * as Highcharts from 'highcharts';

```

Any idea how this could happen?

**Comment by ppotaczek** [comment]
Hi @csprle, 

Thank you for contacting us!

I've tested the newest Highcharts version and everything seems to work as expected. Please check this example:
https://codesandbox.io/s/highcharts-react-demo-pojp7g?file=/demo.jsx

Could you reproduce the issue?

Best regards!

**Comment by csprle** [comment]
I tried to reproduce it within another repository but was not able to. So there seems to be an error on my side. 

Thank you anyways.
